'use client';
import {useMemo,useState} from 'react';
type Item={id:number;name:string;shop:string;cat:string;price:number;rating:number;time:number;emoji:string;offer:string};
const items:Item[]=[
{id:1,name:'Cheese Masala Pav',shop:'Swaad Street Kitchen',cat:'Vadodara Special',price:129,rating:4.8,time:25,emoji:'🥪',offer:'20% OFF'},
{id:2,name:'Gujarati Thali',shop:'Maharaja Bhoj',cat:'Gujarati',price:249,rating:4.9,time:35,emoji:'🍱',offer:'BESTSELLER'},
{id:3,name:'Paneer Tikka Pizza',shop:'Crust & Spice',cat:'Pizza',price:299,rating:4.7,time:30,emoji:'🍕',offer:'15% OFF'},
{id:4,name:'Sev Usal',shop:'Shree Vadodara Snacks',cat:'Gujarati',price:109,rating:4.8,time:20,emoji:'🍲',offer:'LOCAL FAV'},
{id:5,name:'Chicken Biryani',shop:'Royal Hyderabad',cat:'Biryani',price:279,rating:4.8,time:40,emoji:'🍛',offer:'20% OFF'},
{id:6,name:'Cold Coffee',shop:'Bean Theory',cat:'Cafe',price:119,rating:4.6,time:18,emoji:'🥤',offer:'TRENDING'},
{id:7,name:'Veg Hakka Noodles',shop:'Wok Republic',cat:'Chinese',price:189,rating:4.6,time:28,emoji:'🍜',offer:'15% OFF'},
{id:8,name:'Mango Mastani',shop:'Madhav Dairy',cat:'Desserts',price:149,rating:4.9,time:22,emoji:'🥭',offer:'POPULAR'}];
const cats=['All','Vadodara Special','Gujarati','Biryani','Pizza','Chinese','Cafe','Desserts'];
export default function Home(){const[q,setQ]=useState('');const[cat,setCat]=useState('All');const[cart,setCart]=useState<number[]>([]);const[open,setOpen]=useState(false);const[toast,setToast]=useState('');
const list=useMemo(()=>items.filter(x=>(cat==='All'||x.cat===cat)&&(x.name+' '+x.shop+' '+x.cat).toLowerCase().includes(q.toLowerCase())),[q,cat]);
const total=cart.reduce((s,id)=>s+(items.find(x=>x.id===id)?.price||0),0);const add=(id:number)=>{setCart(c=>[...c,id]);setToast('Added to cart');setTimeout(()=>setToast(''),1200)};
return <main><header><div className="logo">S</div><div className="brand">Swaad <span>Vadodara</span></div><nav><button onClick={()=>setCat('All')}>Home</button><button onClick={()=>document.getElementById('restaurants')?.scrollIntoView({behavior:'smooth'})}>Restaurants</button><button onClick={()=>setToast('Free delivery on selected local favourites!')}>Offers</button></nav><button className="cart" onClick={()=>setOpen(true)}>🛒 <b>{cart.length}</b></button></header>
<section className="hero"><div><div className="location">📍 Delivering across Vadodara</div><h1>Vadodara's food,<br/><em>your way.</em></h1><p>From legendary Gujarati favourites to late-night cravings, discover the best food around you.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search for dishes, restaurants..."/><button onClick={()=>document.getElementById('restaurants')?.scrollIntoView({behavior:'smooth'})}>Find food</button></div><div className="stats"><b>4.8★ <small>average rating</small></b><b>25 min <small>fast delivery</small></b><b>500+ <small>local dishes</small></b></div></div><div className="heroArt"><div className="dish">🍛</div><div className="bubble b1">🔥 <b>Popular</b><small>Right now</small></div><div className="bubble b2">⚡ <b>25 min</b><small>Average delivery</small></div></div></section>
<section className="promise"><div>🛵 <b>Fast delivery</b><small>Hot food at your door</small></div><div>❤️ <b>Local favourites</b><small>Made by Vadodara kitchens</small></div><div>💳 <b>Easy checkout</b><small>Simple & secure ordering</small></div></section>
<section id="restaurants" className="content"><div className="heading"><div><span className="eyebrow">DISCOVER</span><h2>Cravings, sorted.</h2><p>Handpicked favourites from around Vadodara.</p></div><div className="cats">{cats.map(c=><button className={cat===c?'sel':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><div className="grid">{list.map(x=><article className="card" key={x.id}><div className="pic"><span>{x.emoji}</span><label>{x.offer}</label><button onClick={()=>add(x.id)}>+</button></div><div className="info"><div className="rating">★ {x.rating}</div><h3>{x.name}</h3><p>{x.shop}</p><div className="bottom"><b>₹{x.price}</b><small>⌁ {x.time} min</small><button onClick={()=>add(x.id)}>Add</button></div></div></article>)}</div>{!list.length&&<div className="empty">No matches found. Try another dish or category.</div>}</section>
<footer><div className="brand"><span className="mini">S</span> Swaad <span>Vadodara</span></div><p>Made for Vadodara, with love.</p><small>© 2026 Swaad Vadodara</small></footer>
{toast&&<div className="toast">✓ {toast}</div>}{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setOpen(false)}>×</button><h2>Your order</h2>{!cart.length?<div className="empty">Your cart is empty.<br/>Add your favourite Vadodara food!</div>:<>{cart.map((id,i)=>{const x=items.find(z=>z.id===id)!;return <div className="row" key={i}><span>{x.emoji}</span><div><b>{x.name}</b><small>{x.shop} · ₹{x.price}</small></div><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}>×</button></div>})}<div className="total"><span>Total</span><b>₹{total}</b></div><button className="checkout" onClick={()=>{setCart([]);setOpen(false);setToast('Order placed! Thank you for choosing Swaad.');setTimeout(()=>setToast(''),2200)}}>Place order →</button></>}</aside></div>}</main>}
